Clobbering of MT slots
koreader/koreader-base pull request #1439
Opened 2021-12-09 16:28 UTC by mapinguari

As per discussion on #1437.

I have made changes to return an fd on device open and to pass the fd that generated the event as part of the lua table returned.

Having made these changes I think it probably is unnecessary to pass the fd with EVERY event as ultimately the [main loop in waitForInput](https://github.com/koreader/koreader-base/blob/1432b9298e8a2ab00aaa2cc52ca14fa90665c70f/input/input.c#L360-L424) only returns a table of event tables for one device at a time, so could have waitForInput return a triple instead. hypothetically.

2021-12-09 18:16 UTC, Frenzie commented on input/input.c
> +        set_event_table(L, event,fd);  // Pushed a new ev table all filled up at the top of the stack (that's -1)
nit, I think clang-format will take care of it by itself?

2021-12-09 18:16 UTC, Frenzie commented on input/input.c
> +                    j = drain_input_queue(L, input_queue, ev_count,inputfds[i], j);
same nit

2021-12-09 18:17 UTC, Frenzie commented on input/input.c
> +		lua_pushnumber(L,inputfds[fd_idx]);
Double nit

2021-12-09 18:18 UTC, Frenzie approved these changes
lgtm besides the formatting nits (spaces for indentation, space after comma), but as I said, clang-format. ^_^

2021-12-09 19:18 UTC, mapinguari commented
ugh sorry. Ok, those should be updated

2021-12-10 00:17 UTC, NiLuJe commented
I'm gonna go with "Not good enough" for now, sorry. (This is just a quick veto to merging this as-is, until I have more than a shower's worth of time to think about it).

In decreasing order of importance:

* This breaks initial sttate handling (I allkuded to this in the other thread). The only way I could think of to avoid that would be to:
* Pass the same info along during the `openInputDevice` code, so that front's init has it on *init*, so it can tweak the initial state appropriately.
* This should probably be using a small-ish seed value in addition to the fd number, because that may be low enough to be lower than the maximum touch points of the input device, which could still leave room for conflicts.
* I like the idea of passing the info along in `w<aitForInput`... as long is it doesn't make the frontend code that much more horrible ;).
* I'd like to see the matching frontend changes before merging this ;).

2021-12-10 00:20 UTC, NiLuJe requested changes
I did it wrong, see above ;p.

(This is just to generate a big red cross to avoid drive-by merges).

2021-12-10 07:55 UTC, mapinguari commented
Ok, points taken. 

I will close this for the moment on my end.

2021-12-10 07:55 UTC, closed without merging

2021-12-10 08:41 UTC, Frenzie commented
> Pass the same info along during the openInputDevice code, so that front's init has it on init, so it can tweak the initial state appropriately.

I thought that was implied by this PR btw.

2021-12-10 12:09 UTC, mapinguari commented
I think my lack of clarity didn't aid this PR.

I was thinking that the fd would just be passed between the C and the lua so that frontend can deal with it as it sees appropriate. Not that the `ABS_MT_SLOT` values would be automatically converted to `ABS_MT_SLOT` + fd (this would obviously cause major differences with handling gestures and the inited state [not that I fully understand what they would be at this point :)]).

This confusion aside however I totally take that the lack of changes on the lua side makes this a bit futile at this point and adds a not insignificant amount to the size of the tables being sent back to lua. So I am happy for this to sit quietly until I have made some changes on the front that either make this PR worthwhile, or change the PR to reduce overhead and satisfy you guys and myself that it isn't going to cause some pernicious issues in the gesture detecting.